### PR TITLE
use nspathcontrol for path popup

### PR DESCRIPTION
**Pull request by avaynshtok**
Great call on the NSPathControl, I didn't know it can take a style of NSPathStylePopUp. I tried it out w/ the default breadcrumb style and it felt too cumbersome when nested 3 or more levels, so I'm sticking w/ the popup style for now. It's very easy to change.

### CODE REVIEW

**Comment by alloy** [comment]
Great, thanks! My last issues are the background color mismatch between the control and the outline view (and actually with the drawer as well) and, more importantly, the control shouldn't become first responder. Care to look into this?

**Comment by alloy** [comment]
Already fixed the questions in my last comment :)

**Comment by avaynshtok** [comment]
Nice! I did play around w/ the background color, but I was trying to match it to the light grey of the drawer and couldn't find a clean way (hardcoding the RGB color didn't seem like the right thing). I think the white works nicely!

**Comment by alloy** [comment]
I think white is the best option indeed and actually the drawer background should match, I’ll try to fix that this week. Thanks again!

**Pull request merged**
