### PR TITLE
Various changes and fixes

### PR DESCRIPTION
**Pull request by datanoise**
Please consider this pull. 

Added:
1. selectInDrawer: action to select a file loaded in the active buffer in the file drawer. This way it's possible to use autocmd like this:
   
   au WinEnter,BufEnter \* macaction selectInDrawer:
2. selectInDrawer: is called automatically when the drawer is opened
3. Added a new menu 'Window/Select File in Drawer' for this action
4. Filter files based on vim's wildignore option
5. Font size is reduced to 11 points. (Personal preference, could be reverted)

Fixes latest changes with new pathComponentPopup:
1. ScollView doesn't fit into the drawer viewport and is displayed clipped at the bottom
2. Since the rootItem is not displayed anymore, changes to the working directory are not being updated in the drawer.

Let me know if you have any questions. Thanks.

### CODE REVIEW

**Comment by alloy** [comment]
Oh sweet, I was putting of figuring out how to make highlighting the current open buffer work (I’m a real vim newb). Right now the path won't merge cleanly because of another change to the working directory control, so I’ll have to find some time tonight, unless you have the time to fix that before then?

On a related note, do you know what the best way would be to find a buffer and close it? (for the rename function)

**Comment by datanoise** [comment]
OK, sending a new pull request. Also I've found a bug in my previous change that would cause MacVim to crash. Fixed.

As for buffer rename. The only way I know would be to run the following vimscript, assuming that you know the old full file name [old_fname] and the new one [new_fname]:

:exec 'bdelete ' . bufname('[old_fname]') | e [new_fname]

But I think that you shouldn't do it in one step. You are probably better to use bufname to figure out if a buffer is loaded and, only then delete it and reopen with a new name. 

I'll see if I can implement it today.

**Comment by datanoise** [comment]
Oh, I didn't know that github can modify the original pull request. Please try to pull it now and see if it merges without conflicts.

Thanks.

**Comment by alloy** [comment]
I like it. A few things to consider, though:
- In my opinion we should always select the file of the current buffer, unless it’s in a collapsed folder in which case there shouldn't be a any files selected.
- When the current buffer is outside of the current working directory using the ‘Select File In Browser’ menu item doesn't actually show it. I see a few solutions:
  - Change the working directory to the directory the file is located in.
  - Don't enable the menu item.
- I wonder if the ‘Buffers’ menu isn’t a better place for the action. Without looking at the changeset it took me a little while to find it in the ‘Window’ menu. It could just be me, do you know of other (Apple) apps that have menu items that select something in a drawer as well?

**Comment by alloy** [comment]
Oh and I forgot to say that I understand the change to 11px, but it’s just too small imo. I reverted it in c51de9e1c2bb431fed04e570166b487e9ce897a6.

**Comment by alloy** [comment]
And another question, it seems `useWildIgnore` is always `YES`, what’s the reason for this?

**Comment by datanoise** [comment]
Yeah, the font size is something that could be taken from MacVim's defaults. 

I was thinking about adding the menu item to Buffers menu, but it looks like this menu is generated on the fly. Take a look at menu.vim. I myself don't like this item handing in the Window menu. All other apps that I know don't need this kind of thing, since they assume that if you selected something, it should be automatically displayed in the drawer. Unfortunately, there is no way to subscribe to this kind of event in MacVim other then using autocmds, which could be considered as a hack.

**Comment by datanoise** [comment]
wildIgnore is YES, by default since I don't see a place where it could be configured, other than defaults again. But YES is the obvious choice, since wildignore usually contains the mask for intermediate files that vim itself ignores by default. NERDTree takes this option into the account as well.

**Comment by datanoise** [comment]
I've been playing with [MMVimController evaluateVimExpression] and it looks like you cannot execute commands like :bdelete using it. I'm not sure what is the better way to implement file rename in this case. You should probably ask Björn Winckler about it.

**Comment by alloy** [comment]
By “MacVim's defaults” do you mean the preference window? Because I don’t think the font size in the drawer warrants an entry there, but I think this something that’s best answered by Björn as well.

I’ll have to look into what `autocmds` are/do.

**Comment by alloy** [comment]
Right, but what I actually meant is, why is there even a `wildIgnore` var? It seems to me that that just is what you’d want, period. So I think we should remove the code that uses that var completely and always ignore.

**Comment by alloy** [comment]
That’s unfortunate, I’ll ask Björn to chip in on the `rename` issue as well. Thanks!

**Comment by datanoise** [comment]
No. I meant to have this option hidden in MacVim defaults. No need to provide any GUI for it in the preferences pane. Just load it using `NSUserDefaults` API and if one wants to change it, they can use `defaults` CLI utility for that.

**Comment by alloy** [comment]
Ah gotcha, yes let’s do that.

**Comment by b4winckler** [comment]
Hi guys.  I have a few remarks.  Note that I have not looked at the code itself, these are just general remarks.
1.  Do _NOT_ use evaluateVimExpression.  I've intended to get rid of this completely for a while now.  It is dangerous for reasons that have to do with distributed objects that I won't got into here.
2.  Using addVimInput: is fine.  Do not rely on it succeeding, however (it may time out, Vim may be in a blocking loop and the message gets dropped, etc.).
3.  I strongly oppose adding preferences (user defaults, Vim options) unless absolutely necessary.  I see no reason to have a UD for wildignore.  A UD for the font size may be warranted, but shouldn't it just be the same size as the Vim view?
4.  The "buffers" menu is a pain in the neck.  I'd avoid modifying it.
5.  A menu item to select file in drawer seems like overkill.  Who would ever use that menu item?  Wouldn't they just click on the file instead?  Is it for the situation when the file isn't actually visible?  I guess that could make sense.  As for putting stuff in the "Window" menu: there should probably be a "View" menu, but I haven't yet had the courage to rearrange Vim's menus too much.

Did I miss something?  Remind me if so.

**Comment by datanoise** [comment]
I've some questions then:
1. If not evaluateVimExpression, then what should we use instead? If I need to get a value of wildignore option for example? Or which file is opened in the current buffer? etc.
2. Good to know.
3. I agree, but if we want the drawer font be the same as a Vim view, we need a way to subscribe to Vim view's font change events. Is there a way to do that?
4. Agree.
5. Yes. If I open a file with command-t plugin that sits deep down in my folders tree, I want it to be visible inside of the drawer, so I can see the file surroundings. I don't like putting this menu item in "Window" menu myself, but I don't see any other better place where to put it. Another option would be to remove it completely and I can just create a keybinding to `macaction selectInDrawer:` command. Not sure if that has more sense.

**Comment by b4winckler** [comment]
There is no way to query arbitrary data from the Vim process apart from evalVimExpr.  You should ask yourself if you _really_ need it though.  I did not look at the code carefully, but I got the impression that you used it to get the buffer number for a file name and then use this to delete a buffer.  The same effect should be possible to achieve using only addVimInput.

The alternative is to add your state to the SetVimStateMsgID dictionary.  Don't go overboard though (by adding lots of state to this message).  I'm not fond of this solution either, but it is safer.

Really, the only way to properly add a feature to MacVim is to put all the logic in the Vim process and make whatever code that goes into the GUI "dumb" (i.e. all state is kept in the Vim process, the GUI process should pass all input to the Vim process and let it act on it, the Vim process then tells the GUI what to do).  The way the file browser code is implemented now completely goes against this paradigm, which is in essence bad.  I have some ideas that I discussed with @alloy to put the logic in the Vim process, but it will be harder to implement, and I still have not sorted out all the details of this.

For now, I'd say do whatever you want.  A "proper" solution will need a refactoring anyway.  At the moment it would be more interesting to see what this feature will look like.  The end result may still be completely usable, but in my experience, sooner or later it will cause bad behavior (i.e. mysterious crashes).

Writing a program like MacVim which separates presentation from logic into different processes is not easy...

**Comment by datanoise** [comment]
Thanks for the explanation! I should really dig more into the MacVim source in order to get a feel of what you are saying here. All I did, I took the code that handles opening files like `[MMAppController filterOpenFiles]` method and used it as an example of how to interact with Vim process. I didn't know that this is not a proper/kosher way to handle things. At this moment I have zero knowledge on how interprocess communication works in MacVim. I can see that this stuff can get very tricky very fast.

Do you have any plain to include this feature into the MacVim proper? 

Thanks for your input.

**Comment by b4winckler** [comment]
The filterOpenFiles code is part of what I would like to rewrite so that it does not use evalVimExpr.  Maybe I was a bit overly dramatic when I said not to use this method -- it used to be that it could wreak havoc but I have taken precautions to guard against this, so it probably is safe to use.  However, I still strongly advice against it as it leads to a coding style that is dangerous.

I fully intend to add the file browser feature to mainline, yes.  Ideally, it would be refactored to live in the Vim process first, but that is something I will have to do and I'm not sure yet when I will get the time.  Maybe as a first step I'll add @alloy's branch and step-by-step replace it.  This remains to be decided.

**Comment by alloy** [comment]
I agree that it should move to the model (the vim process), but, like I discussed with @b4winckler, I wanted to get the features implemented first. Then we’ll all have a better idea of what the requirements are for it to be done “properly” and we can think about the whole “plugin” side of the discussion we’ve had as well and start refactoring.

I’ll read the comments again tomorrow and try to compile a list of questions I still might have. For now, @datanoise, will you take another look at #4 and see if there’s a way to eliminate the use of `evaluateVimExpression:`? And also I’m still wondering why you reverted 2d6ea219599addf8c614dc73707faa9e10ba203e?

**Comment by alloy** [comment]
Hmm, you know what, I’m gonna pull in the changes (related to closing/opening a buffer) from #4 tomorrow anyway and we can go from there.

**Comment by datanoise** [comment]
I agree, to have a prototype is better than nothing. 

I reverted opening the drawer from `selectInDrawer:`, simple because I like to have this `autocmd` in my setup:

`autocmd BufEnter,WinEnter * macaction selectInDraw:`

But that would make the drawer to be opened all the time, which I don't particularly like. So I wanted to have these two actions `openDrawer:` and `selectInDrawer:` separated. Let know know if that makes sense.

**Comment by datanoise** [comment]
As for #4, regardless of what changes you are going to take from this request, you should take a look at [8baadbf](https://github.com/datanoise/macvim/commit/8baadbf0ec3f360600a8e2de37896728a2cd8f23). It fixes a double free bug, which caused numerous crashes for me yesterday.

**Pull request merged**
