### PR TITLE
Split browser

### PR DESCRIPTION
**Pull request by OriPekelman**
Hello I merged the split-browser branch from upstream a month ago, and everything seems to be working fine on Lion, did not test on mountain Lion.

Two tests are failing (51 was already failing on your branch and 34 seems to be a new failure)

### CODE REVIEW

**Comment by alloy** [comment]
Awesome, thanks!

I’ll be using your version this week (on mountain lion) and possibly do another merge (I believe a new snapshot was released in the meantime) before releasing a build of this.

**Comment by alloy** [comment]
I’ve merged the current upstream master as well and pushed it all to the split-browser-update branch.

One TODO is to fix is the use of deprecated APIs on 10.8, I’ll do that somewhere this week.

```
2012-09-03 11:21:11.692 MacVim[5486:707] *** WARNING: -[NSImage compositeToPoint:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
2012-09-03 11:21:11.693 MacVim[5486:707] *** WARNING: -[NSImage compositeToPoint:fromRect:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
```

**Comment by ernie** [comment]
@alloy I didn't see this until now, but I think I just got the deprecations fixed. I'll admit, though, that I haven't done anything with Cocoa in a while, so you'll want to double-check my rects. Will send a PR in a sec.

**Comment by alloy** [comment]
@ernie Thanks! I will work on this later today and hopefully put out a new release.

**Comment by ernie** [comment]
Might wanna hold off. I got my frame wrong after all on the ImageAndTextCell.m file. Working it out now. :P

**Comment by ernie** [comment]
OK, all clear now. Sorry about that earlier mix-up! Yay math.

**Comment by alloy** [comment]
@OriPekelman & @ernie Hey guys, I haven’t pushed a release/build yet, as I decided it was time to [optimise the performance](https://github.com/alloy/macvim/compare/ac6f844d5943d523c321b5c664a5fa6c8cec61d8...3d1fa1c8240aba37ce9e01d41bad055de9bfbb2b) (speed & memory usage), but that work isn’t completely finished yet.

Especially the part about ignoring files that match any of the patterns in `wildignore` is very slow. I still want to support that, but it means I have to somehow bring the pattern matching into the file browser code, instead of checking each file with the vim process. I’m not yet sure if I will either duplicate the code from vim itself, or try to replicate the required parts with a regex.

If you want to try the new code before the release, that would be much appreciated, just to ensure no regressions are introduced.

**Comment by ernie** [comment]
@alloy I've been keeping tabs on the new branch, and wanted to give you a heads up that in the latest changes, a file deleted via a right-click on the file in the browser is not immediately reflected in the interface. A collapse/expand of the containing folder updates the display appropriately. Thanks for your hard work!

**Comment by alloy** [comment]
@ernie Thanks for the heads up! Added to my TODO list.

**Comment by alloy** [comment]
I was unable to fix all the issues in my new code in a timely manner, so I’ve at least put out a release with this update and the NSImage deprecation warnings fix. Sorry for the delay, I should have done it this way from the start.

Thanks for the help, guys!

@ernie I’ll still be working on this on master, so it would be great if you could keep on using that :)

**Comment by alloy** [comment]
@ernie Oops, I meant on the `split-browser` branch, not `master`.

**Pull request closed without merging**
