### PR TITLE
Surface Vertical Split Pref in Preferences

### PR DESCRIPTION
**Pull request by jballanc**
Hidden prefs suck...especially since the file browser open-in-split options make this more useful!

### CODE REVIEW

**Comment by alloy** [comment]
I’ll let Björn decide on this. But could you elaborate on what you mean by “especially since the file browser open-in-split options make this more useful”?

**Comment by jballanc** [comment]
I was referring to the fact that the preference "Open files from applications" --> "in the current window" has the pull-down with the choice "with a split for each file", and that this preference controls how the file split-view opens new files. I prefer new files selected from the list to open in vsplits instead of normal splits.

That said, I have noticed that opening the split-view (with Cmd-Shift-D), then opening two files using vsplits, then closing the split view, has the slightly undesirable effect of only resizing one of the two windows so that you end up with an un-equally split view. It really bothers my OCD tendencies...

I'll see if I can figure out a good way to make that better (the split resizing, that is...I'm perfectly happy being a bit OCD).

**Comment by b4winckler** [comment]
I will think about it.  However, I do not much like the layout of the new prefs.  Maybe it would be nicer to have two separate options in the pull down menu: one for horizontal splits and one for vertical splits?

**Comment by jballanc** [comment]
Cool. I was actually thinking the same thing. Don't know why I thought it would be more difficult to add a choice to the list. I've updated the diff to do it that way now.

**Comment by cristibalan** [comment]
Since you're messing with the prefs, maybe the last option "and set the args list" should be changed to something more clear. It basically opens the file in the current split, but you couldn't tell that by looking at it.

I propose to change it to "in the same split" or "just use :e".

**Comment by alloy** [comment]
I agree with @evilchelu. I have had quite a few people ask me about adding a way to open files in the current view/split, because none of them understood that they had to select ‘and set the arglist’. I was one of those in the beginning as well ;)

I propose something along the lines of ‘in the current view’ / ‘in the current split’.

PS: Out of curiosity I would like to know what ‘and set the arglist’ actually means.

**Comment by b4winckler** [comment]
See `:h arglist`.

I guess this is a bit of an obscure topic that not too many people will know much about.  Perhaps we should change the pref.

**Comment by alloy** [comment]
So basically, if I got it right, it just _happens_ to open one file in the current view, but when opening multiple files this might not work the way the user expects when the pref would say ‘open in current view’. Although I have never run into a problem with it doing something else than I expected, so I wonder if that really matters. I.e. I think using the argument-list makes sense, but advanced users will probably look in that list after opening multiple files (?), whereas new users have no clue and thus the label of the pref should be clearer.

**Comment by b4winckler** [comment]
MacVim sets the arglist using the `:drop` command, so it is no accident that a file opens in the current view (see `:h :drop`).  However, if the current view is modified then a new split will be opened unless the `hidden` option is set.

Also note that if multiple files are opened from the command line then the arglist is also used, so its use sort of permeates Vim.  My idea was that the different ways of opening files should reflect what can be done from the command line (-o / -O / -p / or no switch which is the same as setting the arglist).

I've thought a bit about this and I'm not sure how to express this more succinctly.  It looks weird with "Open files from applications -> in the current window -> in the current view" (I object to repetitions of 'current').  Also, this does not tell you anything about how multiple files are opened (whereas the other options do), which is what I think @alloy was hinting at as well.

I still agree that "set the arglist" is nonintuitive (but this goes for so much in Vim...) so it would be nice to come up with something clearer, but I'm still not sure what that would be.

**Comment by alloy** [comment]
Yep, that’s what I meant and I agree. Let’s mull it over for now.

**Comment by alloy** [comment]
After some discussing with my colleague, @Manfred, we came up with this suggestion:

```
Open files: () in a new window
            () in the current window
        in: - tabs
            - horizontal splits
            - vertical splits
```

The big difference is that ‘in the current window’ would simply work as ‘and set the arglist’ works now, because _all_ of the above options would set the `arglist`. That should cater to users of all levels, no?

I also left out the option in the popup button to ‘open each file in a new window’, because I felt it made the distinction between the first part of the preferences, which deals with windows, and how to open files within those windows a bit fuzzy. Do you know if people actually use that setting?

Finally I also remove ‘from applications’ in the label, because I think it’s redundant and makes it even slightly less clear that it also applies to opening files from the Finder.

**Comment by b4winckler** [comment]
I don't understand exactly what happened to the arglist option?  How can you choose new files to open a new window and set the arglist?

As for the 'each file in a new window' option: somebody did request this option but I can't say I like it much.  One reason it is there is because this is how e.g. TextEdit works.

I don't remember why I wrote "from applications" --- usually I borrow from Apple apps but now I can't find it.  I guess my reasoning might have been that without it there is more chance that a new user thinks that this option affects Vim commands such as `:e` etc.

**Comment by alloy** [comment]
For starters, there was one missing option, which is to open in the active split:

```
Open files: () in a new window
            () in the current window
        in: - active split
            - tabs
            - horizontal splits
            - vertical splits
```

Regarding the ‘arglist’ option; the current ‘and set the arglist’ option would have the same visual behavior as the ‘active split’ option. Furthermore, no matter what options you choose, they would **always** set the `arglist`. I’m not sure why one couldn’t open a new window _and_ set the arglist, is there a vim specific issue why that wouldn’t work? Or maybe I’m just explaining it wrong… which is always a valid option ;)

I feel bad for the user that requested the ‘each file in a new window’ option, but I don’t really like it either. The problem with comparing with apps like TextEdit is that they don’t have tabs/splits etc, which makes sense for general purpose text writing editors, but less for a power editor imo.

Borrowing from Apple is always a good idea, however, since these prefs now also apply to opening files from the file browser, it’s at least misleading in that scenario.

In any case, catering to both advanced vim users and real GUI users is one tough cookie :)

**Pull request merged**
