### PR TITLE
Latest from b4winckler merged into split-browser

### PR DESCRIPTION
**Pull request by stanlemon**

### CODE REVIEW

**Comment by alloy** [comment]
Awesome, thanks!

**Comment by alloy** [comment]
I’ll try to do a release over the weekend.

**Comment by stanlemon** [comment]
@alloy Is a release something I could help you with at all?  If not this round - maybe in the future?  I built it locally so I could use it, so if there are a few extra steps for a release worthy build or anything just let me know and I'm more then willing to contribute.  Thanks for your work on split-browser, I can't tell you enough how much I appreciate using it!

**Comment by alloy** [comment]
@stanlemon That would be great, thanks! I’ve added you as a collaborator, so you should be able to create a ‘release’ and attach a zip to that. It should probably at least include the app bundle, the license, and the `mvim` script.

Be sure to do a clean build and enable all the features, as described in the README for mac osx.

**Comment by stanlemon** [comment]
I have a clean build (using Xcode 5) ready and zipped up… do you want me to make a tag and use GitHub's release process, and if so - how should it be named?

**Comment by alloy** [comment]
I used timestamps in the past, but it might be a good idea to add the upstream MacVim version to it. E.g. MacVim-71-20130920 ? Yeah using a tag and GitHub’s releases is probably easiest for hosting purposes.

**Comment by stanlemon** [comment]
Ok, I think I did it - let me know if I did anything wrong so I can fix it. Thanks! :)

**Comment by alloy** [comment]
The build works for me! I’ve updated the release text a bit by ensuring it didn’t just show this PRs text. Can you send out an announcement tweet with the download location?

**Comment by stanlemon** [comment]
Done, thanks!

**Comment by alloy** [comment]
Thanks _you_! :+1:

**Pull request merged**
