### PR TITLE
Fix for MMVimController#addInput method

### PR DESCRIPTION
**Pull request by datanoise**
I've noticed that file renaming doesn't work correctly. 

When a file is renamed, the old buffer must be deleted with `bwipe!` and a new buffer with a renamed file should be opened. `MMFileBrowserController` implements this functionality correctly by sending two messages consequently via `MMVimController#addInput`. The fist message is to call `MMDeleteBufferByPath` vim function and the second message is `:edit [new_file_name]'. Unfortunately, only the last message gets processed since MMBackend removes all the previous messages with the same ID as an optimization step. 

This patch excludes this optimization for `AddInputMsgID` messages. 

Please review.

### CODE REVIEW

**Comment by b4winckler** [comment]
A good catch, but I do not think this is the proper way to fix this.  Let me think a little bit about a permanent solution to this problem and I'll report back.

**Comment by b4winckler** [comment]
Would it be difficult to combine the two `addInput` calls into one?  For now this would be a better solution.

Modifying `processInput:data:` is rather dangerous and I realize that I have to spend more than just five minutes coming up with a solution.

**Comment by datanoise** [comment]
I believe that how I initially implemented the rename functionality, but later on the thing was split into a separate `deleteBufferByPath` method, so I figured maybe this is the time for a proper fix. Anyway, merging it into one `addInput` call works for me.

**Comment by alloy** [comment]
I have created a patch that moves re-opening a renamed file into the vim function as well: https://gist.github.com/1050809. However, I noticed that the current behavior isn't fully correct because opening the renamed file will happen in the _current_ window/view/tab (whatever the right name is in a vim context), instead of the one that had the old file open.

Example:
- Open two files, in this example foo.txt and bar.txt.
- Select the tab that holds foo.txt.
- Rename bar.txt to baz.txt

The expected result:
- There are still two tabs open
- One for foo.txt and one for the new named file baz.txt
- Also it would probably be best that the tab selection doesn't change, i.e. foo.txt is still the current tab, however that's of less importance right now.

Actual result:
- The tab that showed bar.txt is closed
- The current tab no longer shows foo.txt but the newly named baz.txt

Obviously this is because we simply do `:edit new/file/path`, which will do so in the current window/view/tab.

So the question is, is there a way to open a file in a specific window/view/tab _without_ changing the current shown selection?

Otherwise we probably have to check if the file that is going to be renamed is opened in a window/view/tab, switch selection to it, and only then open the newly named file. Is there a way to do this with or besides -[MMAppController openFiles:withArguments:]?

**Comment by alloy** [comment]
Hmm, actually, let me push this patch as it is a fix for this specific issue and let's discuss the other issue in a new ticket: #28

**Pull request closed without merging**
