### PR TITLE
update to upstream macvim-dev & add context menu entry to make the current file's parent dir the cwd

### PR DESCRIPTION
**Pull request by kjyv**
This adds a menu entry in the context menu to set the the directory of the side bar to the parent directory of the currently visible file. I've found this tremendously useful.

The patch also allows compilation in xcode 4.2.

### CODE REVIEW

**Comment by kjyv** [comment]
update to current master of macvim-dev

**Comment by alloy** [comment]
Hey, this is great, and clearly I’m lagging behind (a few years :stuck_out_tongue: ). I’ll add you as a collaborator so that you can merge yourself next time, sounds good?

**Comment by kjyv** [comment]
Ok, sounds good :)

**Comment by alloy** [comment]
Done :+1:

**Pull request merged**
